### ISSUE TITLE
How to calculate binding score from alphafold-prediction?

### ISSUE THREAD

**Issue by linusbiostat** [phbradley/TCRdock#2]
Hey! I ran the run_prediction.py and got pdb files, and the final tsv with the information about pae, plddt etc. How would I go on from here to calculate binding scores? Thank you!

**Comment by phbradley** [comment]
Hey there, thanks for testing things out. Glad that you were able to generate PDBs and the final TSV file. The raw binding score we use is the mean PAE between pMHC and TCR residues. You can calculate that directly by loading in the PAE matrix from the .npy file with "predicted_aligned_error" in the name, and averaging over the corresponding residue pairs. But the final.tsv file has inter-chain PAE values already stored in there, so to get the pmhc-tcr inter-pae you just need to average these, accounting for the numbers of residues in each chain. Here's a little function that would add a new column with the pmhc-tcr mean PAE values to a pandas dataframe containing the results from the final.tsv file:

```
def add_mhc_tcr_pae_to_results_dataframe(
        results,
        model_name='model_2_ptm',
):
    inter_paes = []

    for _, l in results.iterrows():
        cs = l.target_chainseq.split('/')
        num_chains = len(cs)
        assert num_chains in [4,5] # mhc class 1 or 2

        pmhc_chains = range(num_chains-2)
        tcr_chains = range(num_chains-2, num_chains)

        inter_pae = 0.
        for i in pmhc_chains:
            nres_i = len(cs[i])
            for j in tcr_chains:
                nres_j = len(cs[j])
                pae_ij = l[f'{model_name}_pae_{i}_{j}']
                pae_ji = l[f'{model_name}_pae_{j}_{i}']
                inter_pae += nres_i * nres_j * (pae_ij + pae_ji)
        nres_pmhc = sum(len(cs[x]) for x in pmhc_chains)
        nres_tcr = sum(len(cs[x]) for x in tcr_chains)
        inter_pae /= 2*nres_pmhc*nres_tcr
        inter_paes.append(inter_pae)
    results['pmhc_tcr_pae'] = inter_paes
    return


```

**Comment by phbradley** [comment]
To get a "normalized" binding score like what we use in the decoy discrimination test, you would need pmhc_tcr_pae values for the TCRs and peptides you are interested in, plus at a minimum pmhc_tcr_pae values for those same peptides docked onto a set of background TCRs that are not expected to be specific binders to the peptides. For that you could use the ones included in this repo, at the end of this file:

https://github.com/phbradley/TCRdock/blob/main/datasets_from_the_paper/table_S2_specificity_benchmark_tcrs.csv

You would then subtract off the mean pmhc_tcr_pae for the background TCRs from each peptide's column, and probably also subtract each row's mean value (that's what we did in the paper, anyhow). Here row/column assumes we have a matrix of pmhc_tcr_pae values with rows corresponding to the TCRs of interest and columns corresponding to the peptides of interest.

**Comment by linusbiostat** [comment]
> Hey there, thanks for testing things out. Glad that you were able to generate PDBs and the final TSV file. The raw binding score we use is the mean PAE between pMHC and TCR residues. You can calculate that directly by loading in the PAE matrix from the .npy file with "predicted_aligned_error" in the name, and averaging over the corresponding residue pairs. But the final.tsv file has inter-chain PAE values already stored in there, so to get the pmhc-tcr inter-pae you just need to average these, accounting for the numbers of residues in each chain. Here's a little function that would add a new column with the pmhc-tcr mean PAE values to a pandas dataframe containing the results from the final.tsv file:
> 
> ```
> def add_mhc_tcr_pae_to_results_dataframe(
>         results,
>         model_name='model_2_ptm',
> ):
>     inter_paes = []
> 
>     for _, l in results.iterrows():
>         cs = l.target_chainseq.split('/')
>         num_chains = len(cs)
>         assert num_chains in [4,5] # mhc class 1 or 2
> 
>         pmhc_chains = range(num_chains-2)
>         tcr_chains = range(num_chains-2, num_chains)
> 
>         inter_pae = 0.
>         for i in pmhc_chains:
>             nres_i = len(cs[i])
>             for j in tcr_chains:
>                 nres_j = len(cs[j])
>                 pae_ij = l[f'{model_name}_pae_{i}_{j}']
>                 pae_ji = l[f'{model_name}_pae_{j}_{i}']
>                 inter_pae += nres_i * nres_j * (pae_ij + pae_ji)
>         nres_pmhc = sum(len(cs[x]) for x in pmhc_chains)
>         nres_tcr = sum(len(cs[x]) for x in tcr_chains)
>         inter_pae /= 2*nres_pmhc*nres_tcr
>         inter_paes.append(inter_pae)
>     results['pmhc_tcr_pae'] = inter_paes
>     return
> ```

Perfect, this worked for me! Thank you for the quick response and the function!

**Comment by StysPaul** [comment]
> To get a "normalized" binding score like what we use in the decoy discrimination test, you would need pmhc_tcr_pae values for the TCRs and peptides you are interested in, plus at a minimum pmhc_tcr_pae values for those same peptides docked onto a set of background TCRs that are not expected to be specific binders to the peptides. For that you could use the ones included in this repo, at the end of this file:
> 
> https://github.com/phbradley/TCRdock/blob/main/datasets_from_the_paper/table_S2_specificity_benchmark_tcrs.csv
> 
> You would then subtract off the mean pmhc_tcr_pae for the background TCRs from each peptide's column, and probably also subtract each row's mean value (that's what we did in the paper, anyhow). Here row/column assumes we have a matrix of pmhc_tcr_pae values with rows corresponding to the TCRs of interest and columns corresponding to the peptides of interest.

If, in your pmhc_tcr_pae value matrix, the rows correspond to the TCRs of interest and the columns correspond to the peptides of interest, where do you fill in the mhc information? with the TCRs? the peptides? or in a third dimension?

I've done tests that vary the 3 parameters (mhc, peptide, TCR (and also the alleles of the VJ genes)). For a given TCR, I obtain groups of pae values per peptide, then sub-groups per MHC and then VJ gene allele sub-sub-groups (the VJ gene version is the same, e.g. TRBV19 with 3 alleles 1, 2 and 3). MHC has some influence on docking (as expected).

**Comment by phbradley** [comment]
Hi Paul, sorry for missing this the first time! In the original elife study, the columns correspond to peptide-MHCs, so the MHC information was linked to the peptide. There were only two MHCs (A*02:01 and H2Db) and a smallish number of peptides so I'm not sure the stats were sufficient to look into MHC-specific effects, but I agree with you that it would be interesting to consider. For example, perhaps one can predict MHC restriction even in some cases where the precise peptide restriction is uncertain.
