### ISSUE TITLE
TypeError in run_prediction.py

### ISSUE THREAD

**Issue by InfoSuresh** [phbradley/TCRdock#4]
@phbradley 
I am not able to execute run_prediction.py script. I am getting the following error.

**TypeError: Haiku now requires the split_rng argument to be passed to hk.vmap. If you have code using the old API which you cannot change, you can opt-out of this requirement by using `hk.vmap.require_split_rng = False`**

Pls, give the exact versions of the packages.
How to resolve this?
Thank you

**Comment by phbradley** [comment]
Hi there,
Thanks for trying the code. The haiku version I am using is "0.0.4". Have you tried following their suggestion, i.e., at the top of `run_prediction.py` adding:

```
import haiku as hk
hk.vmap.require_split_rng = False
```

If that fixes it, we could add that to the repository.

Thanks,
Phil

**Comment by InfoSuresh** [comment]
@phbradley 
Thanks. It's working now.
