### ISSUE TITLE
Content of pdb files before and after running docking

### ISSUE THREAD

**Issue by Florian411** [phbradley/TCRdock#9]
Hello,

I have been looking at working with the docked structures stored in the pdb files generated by TCRDock. 

Playing around with the example files, e.g. T00000_B3501_MGSLEMVPM_0_0.pdb used as input, i could not find the epitope sequence in the pdb file, instead there is LPPLDITPY.

For the output (test_run_single_T00000_B3501_MGSLEMVPM_0_model_1_model_2_ptm.pdb), i do not have 4 separate chains anymore in the pdb file, instead I can load a single chain of 412 residues.

I am wondering whether
1. only the peptide found in the reference is used for docking and not the query epitope, and 
2. if the query epitope is actually used, where it is stored in both input and output pdbs.

Thanks in advance for helping out!

**Comment by phbradley** [comment]
Hi Florian,
Thanks for trying things out. The input (template) files for the AlphaFold modeling will have the original sequences of their source PDB files, not the target epitope sequence. The output pdb files should definitely have the target epitope as the peptide sequence. Unfortunately, the AlphaFold modeling does not preserve the chain identifiers, so the output pdbs are all chain 'A' (but there are 200 residue gaps in the numbering between chains). If you open them up in the a molecular viewer they should look like ternary complexes with four (or five) separate chains.
Hope that clarifies things.
Take care,
Phil

________________________________
From: Florian Schmidt ***@***.***>
Sent: Thursday, November 16, 2023 11:01 PM
To: phbradley/TCRdock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [phbradley/TCRdock] Content of pdb files before and after running docking (Issue #9)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hello,

I have been looking at working with the docked structures stored in the pdb files generated by TCRDock.

Playing around with the example files, e.g. T00000_B3501_MGSLEMVPM_0_0.pdb used as input, i could not find the epitope sequence in the pdb file, instead there is LPPLDITPY.

For the output (test_run_single_T00000_B3501_MGSLEMVPM_0_model_1_model_2_ptm.pdb), i do not have 4 separate chains anymore in the pdb file, instead I can load a single chain of 412 residues.

I am wondering whether

  1.  only the peptide found in the reference is used for docking and not the query epitope, and
  2.  if the query epitope is actually used, where it is stored in both input and output pdbs.

Thanks in advance for helping out!

**Comment by Florian411** [comment]
Thank you very much. This helped a lot :-) Problem solved.
